### ISSUE TITLE
Creating v-interfaces for use as part of docker-compose networking

### ISSUE THREAD

**Issue by hllhll** [oofnikj/docker-openwrt#10]
Hi,

My personal holy grail is to make openwrt as a router+fw, where I can place different docker containers behind and configure routes and fw via openwrt. I wouldn't like for the containers to be exposed to the "default" docker/compose stack,rather be as sort of "virtual" interface that the open wrt would see it as a real one hence can route and fw each independently.
in your make run script your doing all sort of magic in the networking that works awesome!
how do you think I could go around and combine similar functionality of the make run script, with more containers, running as a docker-compose suite that would tie the interfaces the way described above? (+also allow `raw` wifi access as `make run` does now)

**Comment by oofnikj** [comment]
Hi @hllhll, you can define your docker-compose network like the following:
```yaml
services:
  some-service:
  ...
    networks:
      openwrt-lan:
        ipv4-address: '192.168.whatever.some_valid_address'
networks:
  openwrt-lan:
    external: true
```
This will connect `some-service` to your pre-existing `openwrt-lan` network, and be visible to any hosts, containerized or physical, who are on the same network.
