### ISSUE TITLE
Install monitoring with physical OpenWrt device

### ISSUE THREAD

**Issue by darrepac** [oofnikj/docker-openwrt#22]
Hello

I am a bit lost.
I have already a running openwrt router so I am not interested by the openwrt part of this repo but the grafana part... yet it is in the same repo so I wonder if I can only use grafana part and how to install it.
I guess that influxdb and grafana are part of the container so what IP adress should I put in the .env file...
Well as you understand, I don't understand :)

**Comment by oofnikj** [comment]
Yes, it's possible.

The instructions for setting up the monitoring components are independent from the Docker stuff in the main part of the repository. You just need to make sure that your instances of InfluxDB and Grafana are properly accessible on the network. 

If you use the Docker Compose script provided, you'll need to modify it slightly by removing the `external: true` specification on the `openwrt-lan` network which will instruct Docker to create a bridge network with this name instead of expecting it to exist already. In addition, you will need port forwarding so that the host on which the services are running can communicate properly with OpenWrt. Grafana by default listens on port 3000. InfluxDB listens by default on ports 8086 (API) and for collectd metrics on port 25826 per the config file `influxdb.conf`.

Let's say you are running OpenWrt on 192.168.0.1, and your monitoring server on 192.168.0.2. Your Docker Compose script might look something like this:
```yaml
version: "3"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.5
    networks:
      openwrt-lan:
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboard-openwrt.json:/var/lib/grafana/dashboards/dashboard-openwrt.json"
    restart: always

  influxdb:
    container_name: influxdb
    image: influxdb:1.7
    networks:
      openwrt-lan:
    ports:
      - "8086:8086"
      - "25826:25826"
    env_file: 
      - .env
    volumes:
      - "./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "./influxdb/types.db:/usr/share/collectd/types.db"
      - "influxdb:/var/lib/influxdb"
    restart: always

networks:
  openwrt-lan:

volumes:
  influxdb:
```

We omit the `ipv4_address` static configuration here and instead allow Docker to assign an IP address automatically to our containers. We don't really care what they are since we are forwarding ports to the host. You then point your OpenWrt router to send collectd metrics to 192.168.0.2:25826. With any luck, Grafana will show up at `http://192.168.0.2:3000` and ask for the credentials you set in `.env`.
